services:
  php:
    build:
      args:
        user: www
        group: www
        uid: 1000
        gid: 1000
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www
    container_name: easyCode_php
    depends_on:
      - postgres
  nginx:
      image: nginx:stable-alpine
      ports:
          - ${APP_PORT:-80}:80
      volumes:
          - .:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      container_name: easyCode_nginx
      depends_on:
          - php
  node:
    stdin_open: true
    build:
      args:
        user: node
      context: .
      dockerfile: docker/node.Dockerfile
    volumes:
      - .:/var/www
    container_name: easyCode_node
    ports:
      #For vite-server
      - ${VITE_PORT:-5173}:5173
  postgres:
    image: postgres:17.0
    ports:
      - ${PG_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: easyCode_postgres
  redis:
      image: redis:7.4
      container_name: easyCode_redis
      ports:
          - ${REDIS_PORT:-6379}:6379
      volumes:
          - redisdata:/data

volumes:
  pgdata:
  redisdata:
